### ISSUE TITLE
Use of type synonyms in Network.Tox.C.Tox

### ISSUE THREAD

**Issue by adscadscfr** [TokTok/hs-toxcore-c#44]
When browsing ``Network.Tox.C.Tox`` you see many type synonyms like

    type FriendConnectionStatusCb a = Tox a -> Word32 -> Connection -> a -> IO a

I would say: leave the signature long-hand; it might be longer to type but much cleared when browsing haddock documentation.

**Comment by iphydf** [comment]
I've removed all callbacks and replaced them with an event sum type.
